// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck.Data;

#nullable disable

namespace Truck.Data.Migrations
{
    [DbContext(typeof(TruckDbContext))]
    partial class TruckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Truck.Data.Entities.CompanyStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompaniesStocks");
                });

            modelBuilder.Entity("Truck.Data.Entities.CompanyStock_Shipment", b =>
                {
                    b.Property<int>("Shipment_Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyStock_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyStokId")
                        .HasColumnType("int");

                    b.HasKey("Shipment_Id", "CompanyStock_Id");

                    b.HasIndex("CompanyStokId");

                    b.ToTable("CompaniesStocks_Shipments");
                });

            modelBuilder.Entity("Truck.Data.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DriverPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Truck.Data.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfStock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MainTruckAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckCompanyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckCompanyPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrucksCompanies");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany_Driver", b =>
                {
                    b.Property<int>("Driver_Id")
                        .HasColumnType("int");

                    b.Property<int>("TruckCompany_Id")
                        .HasColumnType("int");

                    b.HasKey("Driver_Id", "TruckCompany_Id");

                    b.HasIndex("TruckCompany_Id");

                    b.ToTable("TruckCompanies_Drivers");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany_Shipment", b =>
                {
                    b.Property<int>("Shipment_Id")
                        .HasColumnType("int");

                    b.Property<int>("TruckCompany_Id")
                        .HasColumnType("int");

                    b.HasKey("Shipment_Id", "TruckCompany_Id");

                    b.HasIndex("TruckCompany_Id");

                    b.ToTable("TruckCompanies_Shipments");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany_Vehicle", b =>
                {
                    b.Property<int>("Vehicle_Id")
                        .HasColumnType("int");

                    b.Property<int>("TruckCompany_Id")
                        .HasColumnType("int");

                    b.HasKey("Vehicle_Id", "TruckCompany_Id");

                    b.HasIndex("TruckCompany_Id");

                    b.ToTable("TruckCompanies_Vehicles");
                });

            modelBuilder.Entity("Truck.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiscenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Truck.Data.Entities.CompanyStock_Shipment", b =>
                {
                    b.HasOne("Truck.Data.Entities.CompanyStock", "CompanyStok")
                        .WithMany()
                        .HasForeignKey("CompanyStokId");

                    b.HasOne("Truck.Data.Entities.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("Shipment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyStok");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany_Driver", b =>
                {
                    b.HasOne("Truck.Data.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("Driver_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Truck.Data.Entities.TruckCompany", "TruckCompany")
                        .WithMany()
                        .HasForeignKey("TruckCompany_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TruckCompany");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany_Shipment", b =>
                {
                    b.HasOne("Truck.Data.Entities.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("Shipment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Truck.Data.Entities.TruckCompany", "TruckCompany")
                        .WithMany()
                        .HasForeignKey("TruckCompany_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("TruckCompany");
                });

            modelBuilder.Entity("Truck.Data.Entities.TruckCompany_Vehicle", b =>
                {
                    b.HasOne("Truck.Data.Entities.TruckCompany", "TruckCompany")
                        .WithMany()
                        .HasForeignKey("TruckCompany_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Truck.Data.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TruckCompany");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
